# Generated by Django 6.0.1 on 2026-01-07 17:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=255)),
                ('total_seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trains',
                'indexes': [models.Index(fields=['train_number'], name='trains_train_n_28690f_idx'), models.Index(fields=['is_active'], name='trains_is_acti_dd9ddc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('runs_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trains.train')),
            ],
            options={
                'db_table': 'train_schedules',
            },
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_seats', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='trains.trainschedule')),
            ],
            options={
                'verbose_name_plural': 'Seat availabilities',
                'db_table': 'seat_availability',
            },
        ),
        migrations.AddIndex(
            model_name='trainschedule',
            index=models.Index(fields=['train', 'runs_on'], name='train_sched_train_i_d4bd28_idx'),
        ),
        migrations.AddIndex(
            model_name='trainschedule',
            index=models.Index(fields=['source', 'destination', 'runs_on'], name='train_sched_source_9a1c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainschedule',
            index=models.Index(fields=['runs_on'], name='train_sched_runs_on_eea9bd_idx'),
        ),
    ]
